version: "3.9"

services:
  orderly-db:
    image: postgres:16.0
    restart: always
    container_name: orderly-postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: orderly
      PGDATA: /data/postgres
    networks:
      - orderly-network
    ports:
      - 5432:5432
    volumes:
      - ./data/pg:/data/postgres
  orderly-server:
    build: .
    image: orderly-api:1.0.0
    container_name: orderly-api
    environment:
      DATABASE_URL: postgresql://dev:docker@orderly-db:5432/orderly?schema=public
    command: npm run start:dev
    volumes:
      - .:/usr/src/app:rw
    networks:
      - orderly-network
    ports:
      - 8080:8080
      - 9229:9229
    depends_on:
      - orderly-db
      
networks:
  orderly-network:
    driver: bridge
